# The parameters are the absolute paths. Do not include the "/" at the end of the paths.
input          : "/full_path_to/Dev_DaytonaPb/hifireads_dem"
probe     : "/full_path_to/Dev_DaytonaPb/enrichment_probes"
output    : "/full_path_to/Dev_DaytonaPb/output"
reference      : "/full_path_to/Dev_DaytonaPb/reference"
# comma separated list of SOTCs to screen, default as "S:L452R,S:E484K"
sotc : "S:L452R,S:E484K"


